# Generated by Django 5.0.3 on 2024-03-26 08:59

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+254722200000",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
