# Generated by Django 5.0.3 on 2024-03-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="photo1",
            field=models.ImageField(
                blank=True, default="/interior_sample.jpg", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="photo2",
            field=models.ImageField(
                blank=True, default="/interior_sample.jpg", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="photo3",
            field=models.ImageField(
                blank=True, default="/interior_sample.jpg", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="photo4",
            field=models.ImageField(
                blank=True, default="/interior_sample.jpg", null=True, upload_to=""
            ),
        ),
    ]
