# Generated by Django 5.0.3 on 2024-03-26 08:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_property_photo1_alter_property_photo2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True, editable=False, populate_from="title", unique=True
            ),
        ),
    ]
